[
  {
    "titulo": "Cuenta Premium Netflix 1 Mes",
    "precio": 7.99,
    "cantidad": 50,
    "descripcion": "Acceso a una cuenta premium de Netflix válida por 1 mes.",
    "imagenes": ["img1.1.webp", "img1.2.webp", "img1.3.webp"],
    "categoria": "Streaming",
    "plataforma": "Netflix",
    "stock": 50,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 5,
    "likes": 210,
    "dislikes": 4,
    "etiquetas": ["netflix", "streaming", "cuenta"]
  },
  {
    "titulo": "Key Steam - Grand Theft Auto V",
    "precio": 14.99,
    "cantidad": 30,
    "descripcion": "Clave digital para activar Grand Theft Auto V en Steam.",
    "imagenes": ["img2.1.webp", "img2.2.webp"],
    "categoria": "Videojuegos",
    "plataforma": "Steam",
    "stock": 30,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 5,
    "likes": 180,
    "dislikes": 2,
    "etiquetas": ["steam", "gta", "key"]
  },
  {
    "titulo": "Licencia Microsoft Office 365 Personal 1 Año",
    "precio": 29.99,
    "cantidad": 20,
    "descripcion": "Licencia original de Office 365 Personal válida por 1 año.",
    "imagenes": ["img3.1.webp", "img3.2.webp", "img3.3.webp"],
    "categoria": "Software",
    "plataforma": "Windows/Mac",
    "stock": 20,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 4,
    "likes": 120,
    "dislikes": 5,
    "etiquetas": ["office", "licencia", "microsoft"]
  },
  {
    "titulo": "Cuenta Spotify Premium 3 Meses",
    "precio": 12.0,
    "cantidad": 40,
    "descripcion": "Cuenta de Spotify Premium válida por 3 meses.",
    "imagenes": ["img4.1.webp", "img4.2.webp"],
    "categoria": "Streaming",
    "plataforma": "Spotify",
    "stock": 40,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 5,
    "likes": 160,
    "dislikes": 3,
    "etiquetas": ["spotify", "premium", "cuenta"]
  },
  {
    "titulo": "Key Steam - Red Dead Redemption 2",
    "precio": 19.99,
    "cantidad": 15,
    "descripcion": "Clave digital para activar Red Dead Redemption 2 en Steam.",
    "imagenes": ["img5.1.webp", "img5.2.webp"],
    "categoria": "Videojuegos",
    "plataforma": "Steam",
    "stock": 15,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 5,
    "likes": 140,
    "dislikes": 1,
    "etiquetas": ["steam", "rdr2", "key"]
  },
  {
    "titulo": "Licencia Windows 10 Pro",
    "precio": 15.0,
    "cantidad": 25,
    "descripcion": "Licencia original para activar Windows 10 Pro.",
    "imagenes": ["img6.1.webp", "img6.2.webp"],
    "categoria": "Software",
    "plataforma": "Windows",
    "stock": 25,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 4,
    "likes": 100,
    "dislikes": 6,
    "etiquetas": ["windows", "licencia", "pro"]
  },
  {
    "titulo": "Cuenta Disney+ 1 Año",
    "precio": 29.99,
    "cantidad": 10,
    "descripcion": "Acceso a una cuenta Disney+ válida por 1 año.",
    "imagenes": ["img7.1.webp", "img7.2.webp"],
    "categoria": "Streaming",
    "plataforma": "Disney+",
    "stock": 10,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 5,
    "likes": 90,
    "dislikes": 2,
    "etiquetas": ["disney", "streaming", "cuenta"]
  },
  {
    "titulo": "Key Steam - Cyberpunk 2077",
    "precio": 17.5,
    "cantidad": 18,
    "descripcion": "Clave digital para activar Cyberpunk 2077 en Steam.",
    "imagenes": ["img8.1.webp", "img8.2.webp"],
    "categoria": "Videojuegos",
    "plataforma": "Steam",
    "stock": 18,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 4,
    "likes": 110,
    "dislikes": 3,
    "etiquetas": ["steam", "cyberpunk", "key"]
  },
  {
    "titulo": "Licencia Adobe Photoshop CC 1 Año",
    "precio": 49.99,
    "cantidad": 8,
    "descripcion": "Licencia válida por 1 año para Adobe Photoshop CC.",
    "imagenes": ["img9.1.webp"],
    "categoria": "Software",
    "plataforma": "Windows/Mac",
    "stock": 8,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 5,
    "likes": 70,
    "dislikes": 1,
    "etiquetas": ["adobe", "photoshop", "licencia"]
  },
  {
    "titulo": "Cuenta HBO Max 6 Meses",
    "precio": 18.0,
    "cantidad": 12,
    "descripcion": "Cuenta de HBO Max válida por 6 meses.",
    "imagenes": ["img10.1.webp", "img10.2.webp"],
    "categoria": "Streaming",
    "plataforma": "HBO Max",
    "stock": 12,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 4,
    "likes": 80,
    "dislikes": 2,
    "etiquetas": ["hbo", "streaming", "cuenta"]
  },
  {
    "titulo": "Key Steam - FIFA 24",
    "precio": 21.0,
    "cantidad": 20,
    "descripcion": "Clave digital para activar FIFA 24 en Steam.",
    "imagenes": ["img11.1.webp"],
    "categoria": "Videojuegos",
    "plataforma": "Steam",
    "stock": 20,
    "fecha": { "$date": "2025-05-19T00:00:00.000Z" },
    "rating": 4,
    "likes": 60,
    "dislikes": 2,
    "etiquetas": ["steam", "fifa", "key"]
  }
]
